### ISSUE TITLE
[BUG] (Reopening) Spectator/active-game endpoint returning 404 whereas the player is ingame (EUW & NA - 100% of the time)

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#266]
Hey guys

(Reopening #165)

For the past few hours, spectator endpoint in EUW and NA returns http404 whereas the player is ingame.

It has been affecting 100% of the lookups in NA and EUW.

Could you have a look please ?

Thanks :)

**Comment by bangingheads** [comment]
Spectating is disabled in client, I'd assume this is effecting Spectator-V4 as well

**Comment by stelar7** [comment]
@RiotR1cket

**Comment by RiotR1cket** [comment]
Hey folks,

Spectator had issues with this latest patch in these regions. As @bangingheads noticed, we disabled spectator in client in order to prevent a poor player experience, and we also simultaneously disabled the spectator grid entirely as we investigated. We have identified the cause and turned back on the Riot API spectator APIs as of a few minutes ago. We do not anticipate needing to turn it back off. Client spectate remains disabled while we fix the root cause, this should no longer affect the data coming into the spectator grid and being made available via Riot API.

Sorry for the outage and thanks for your patience.

**Comment by trebonius0** [comment]
No problem, thanks for the quick notice :)
Closing the issue now

**Comment by trebonius0** [comment]
Reopening has the issue started to occur again on EUW only. 
I've noticed a raise of errors to ~15% of the calls in the past hour. 
Any update @RiotR1cket ?

Thanks

**Comment by RiotR1cket** [comment]
Thanks for the report, this is fixed as of 2 hours ago from time of this comment.

**Comment by trebonius0** [comment]
@RiotR1cket Sadly, the error rate is still around ~17h for the past hour

**Comment by trebonius0** [comment]
@RiotR1cket Additional info which might help you. (as it might be a root cause of the issue).
Today, spectator mode is still buggy in the lol ingame client in EUW: I've this friend who appears as being online 
![image](https://user-images.githubusercontent.com/14201457/79575030-659c3180-80c1-11ea-8b43-ff9b644b899e.png) but, as you can see the game duration is not displayed. 

The "spectate game" option is not greyed out. So I tried to start a replay, which lead to a black screen and an error window telling me that it couldn't grab data from servers

Here is the command line it started to grab the replay
`"D:/Riot Games/League of Legends/Game/League of Legends.exe" "spectator 185.40.64.163:80 J+LrV2pv0vpBI0xQK3Tx8uzAufZ5nhQN 4538297594 EUW1" "-PlayerID=23812722" "-GameID=4538297594" "-GameBaseDir=D:\Riot Games\League of Legends" "-Region=EUW" "-Locale=fr_FR" "-SkipBuild" "-EnableCrashpad=true" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=53219" "-RiotClientAuthToken=xXwosUjz-mJZekb6v6NKWw"`

Thanks !

**Comment by RiotR1cket** [comment]
Hey thanks again, we fixed some firewall rules for a segment of game servers as of 2hr ago. I still had a bookmark of your debug page and it does reflect the fix. It's very useful to have a metric from outside of our own systems :) It's been really bad luck to hit three totally separate issues in the span of a few days, after we've had so many months of full function. Let's all hope it holds up at least through the weekend....

**Comment by trebonius0** [comment]
Thanks a lot for the fix !
Glad you still had this page bookmarked :)

I'll follow up a little bit in the next hours and if the issue doesn't reappear by Monday I'll close this bug

**Comment by trebonius0** [comment]
Issue didn't reappear, closing the bug
