### ISSUE TITLE
[BUG] Wrong splasharts in cdn

### ISSUE THREAD

**Issue by i32ropie** [RiotGames/developer-relations#348]
**Bug Description**  
There are, at least, 8 wrong splasharts in the cdn

**Problem Description**  
The following splash images:
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_36.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_10.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lillia_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_8.jpg

Show the default splash image, not the one that should be showing. They are also wrong in the tarball.

**Expected Result**  
The links and the tarball should show the correct images

**Actual Result**  
The actual result is the default skin of the champion

**Comment by MingweiSamuel** [comment]
Related past issues:

#308 #284 #292

#309

**Comment by MingweiSamuel** [comment]
As we know this also breaks the League of Legends website: https://na.leagueoflegends.com/en-us/champions/teemo/

**Comment by i32ropie** [comment]
With the new patch 10.16, all the new skins have the same problem

**Comment by RiotTuxedo** [comment]
This is being looked into. Should be resolved in 10.18.

**Comment by i32ropie** [comment]
Hi,

With the new patch 10.18 it got solved for those skins, but all the new ones included in this patch have the same issue:

https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg

**Comment by i32ropie** [comment]
Hi!

Just checked and they are still wrong. With the new patches, new skins were realeased and some are also wrong at ddragon. I will list all the wrong splasharts I found:

https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_8.jpg (Shows a black img with the text: PLACEHOLDER)
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_9.jpg (Shows a black img with the text: PLACEHOLDER)
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_23.jpg (Shows a black img with the text: PLACEHOLDER)
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_31.jpg (Shows a black img with the text: PLACEHOLDER)
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_29.jpg (Shows a black img with the text: PLACEHOLDER)
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_35.jpg (Shows the same as 18 instead of the prestige one)

**Comment by bangingheads** [comment]
Although this issue is for splashes, there is more wrong than just splashes. Running image comparison with CDragon this is the list of currently incorrect unversioned image assets:

https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_7.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_7.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_31.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_35.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ahri_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ashe_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Cassiopeia_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kindred_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Leblanc_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/LeeSin_31.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sett_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Shen_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Viktor_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Yasuo_35.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ziggs_23.jpg

**Comment by bangingheads** [comment]
10.21 I notice some like Sett_9 loading was fixed. New skins are showing as placeholders.

Updated list of images, ignoring Fiddle as they are correct for FiddleSticks, they were in the other list as they still exist.

https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_24.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_60.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_31.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_13.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_35.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Aatrox_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ahri_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Amumu_24.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ashe_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Cassiopeia_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Elise_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fizz_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Karma_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kassadin_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Khazix_60.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kindred_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Leblanc_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/LeeSin_31.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sett_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Shen_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sivir_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/TwistedFate_13.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Viktor_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Yasuo_35.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ziggs_23.jpg

**Comment by bangingheads** [comment]
10.22 brings it to 73 images with issues. None resolved since last patch with these issues added:

https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_28.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_32.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ahri_28.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Akali_32.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kaisa_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kaisa_27.jpg

**Comment by itachi42** [comment]
While I understand listing them makes it easier for you to track what is not fixed, isn't this more complicated for Riot to follow ?

**Comment by bangingheads** [comment]
Patch 11.1 130 images missing/incorrect.

https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_28.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_32.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_24.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_13.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_10.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_60.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kled_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_31.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_12.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_24.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nasus_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_18.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_10.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_13.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vladimir_21.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_35.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yorick_12.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_7.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Aatrox_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ahri_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ahri_28.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Akali_32.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Amumu_24.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Anivia_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ashe_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/AurelionSol_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Azir_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Brand_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Cassiopeia_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Diana_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Diana_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Elise_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_22.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_23.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fizz_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Gragas_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Hecarim_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Illaoi_10.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ivern_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Janna_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Jayce_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kaisa_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kaisa_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kalista_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Karma_26.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kassadin_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Katarina_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kayle_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Khazix_60.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kindred_3.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kled_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Leblanc_29.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/LeeSin_31.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lissandra_12.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lucian_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MasterYi_33.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nami_24.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nasus_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nidalee_18.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ornn_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pyke_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Qiyana_11.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Rakan_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sett_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sett_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Singed_10.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sivir_25.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sona_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Soraka_17.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/TwistedFate_13.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vi_20.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Viktor_5.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vladimir_21.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Xayah_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/XinZhao_27.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Yasuo_35.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Yorick_12.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zac_7.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zed_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ziggs_23.jpg

**Comment by bangingheads** [comment]
11.3 resolved these issues except our Samira tiles which still appear as Sett.

https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_1.jpg

**Comment by Vianpyro** [comment]
Maybe [this issue (#470)](https://github.com/RiotGames/developer-relations/issues/470) should be mentioned in here ?

**Comment by i32ropie** [comment]
I think all cnd problems were already fixed, so I'm closing this issue. Thank you all!
