### ISSUE TITLE
Third-party code endpoint not working (esp on OCE)

### ISSUE THREAD

**Issue by jjmaldonis** [RiotGames/developer-relations#72]
There have been a few reports of the third-party code endpoint not working.

@ molenzwiebel mentioned this a few days ago, saying that his users were reporting issues, and today @ DPS Centrix said: "from what I see in my test environment OCE is always down, or at least so often that every time I check it is. Other platforms have the occasional hickup but work fine".

**Comment by molenzwiebel** [comment]
Can confirm! I've had numerous reports over the last few days, from users in OCE, EUW and NA.

**Comment by jluzonpr** [comment]
Misconfiguration on our end for OCE. Should be fixed now.

**Comment by molenzwiebel** [comment]
This is still happening across a variety of servers. The verification service is simply way too unstable right now to use in anything without providing an alternative way to verify accounts.

Over the last week I've gotten 4 different people telling me verification didn't work for them even after multiple restarts and trying on different days/times.

**Comment by RiotTuxedo** [comment]
I think we want to go ahead and separate these issues. Part of the reason it took so long to look into the issue with OCE was that it was conflated with the persisting issue of this endpoint's unreliability. The issue with OCE would have likely got escalated if the ticket was "third-party-code-v3 has stopped working as of {date} in OCE" and another ticket with "third-party-code-v3 has inconsistent results with some players never being able to validate themselves".

I know we've gone down this path before, so I appreciate the patience. Can you create a ticket specifically calling out the unreliability of the third party code endpoint and provide summoner names and regions. I've got a hunch about this issue, but I want to wait to describe it until the new issue is created.
