### ISSUE TITLE
[BUG] Account Endpoints return 401 without any reason

### ISSUE THREAD

**Issue by Henrik-3** [RiotGames/developer-relations#768]
**Bug Description**  

Several account endpoints randomly return a 401 error code for no apparent reason. 
Seems to only occur in the `Europe` cluster at the moment. 
Known on the following endpoints:
- [/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}](https://developer.riotgames.com/apis#account-v1/GET_getByRiotId)
- [/riot/account/v1/active-shards/by-game/{game}/by-puuid/{puuid}](https://developer.riotgames.com/apis#account-v1/GET_getActiveShard)

(may also affect the other account endpoints, but this is not confirmed)

**Problem Description**  
I am unable to retrieve account data while this error occurs for some users

**Expected Result**  
Do not return a 401 error if the request was made correctly with all required headers, etc.
If an error occurs, the correct error code should be returned.

**Actual Result**  
![image](https://github.com/RiotGames/developer-relations/assets/43936184/11d180cb-aec7-4dfe-934a-cb19fb7ba379)
![image](https://github.com/RiotGames/developer-relations/assets/43936184/7e5e8151-1c56-47a4-a293-39a40afa6623)

As you can see, the request is completely identical, to get the correct result between these screenshots, I needed 6 requests

**Developer Impact**  
* Frequency: Every second request (approximately, seems random).
* Severity: My bot can't return a match list/stats if username lookup is not possible.
* Efficiency:  I have to repeat the request until I get the right result, which results in a higher server load on your side as i need more requests to get a result.

**Player Impact**  
* Frequency: 50% of all users are affected
* Region: All users are currently affected.

**Preconditions and Repro Steps**  
Just try to run the API call several times

**Comment by geozukunft** [comment]
Can repro. From my quick tests I can't say for sure how many % of requests this affects as it sometimes seems to respond multiple times with 401 or multiple times work with code 200 but definitly reproducable. 

Labels: Valorant API, BUG, API BUG,

**Comment by f3ar161** [comment]
We've identified the root cause, Issue is solved, 401 error response is now down to 0.

**Comment by fireinnti** [comment]
@f3ar161 I'm still getting Unauthorized on random calls. Sometimes it works sometimes it doesn't, its a 400 error not a 401 for me. 

```
local.INFO: ARG4cv13COvE7a2QxJk6ryz06biOuLW9obydTXsHO6criotclientsecret .  

   WARN  local.INFO: dWUxOk10UzI5THZpcEJzaGsxQ3BXOTZYVUEuSi1OWnFYSnpCMTlabUhTTmlkdGhxUQ==code .  

   WARN  local.ERROR: Client error: `POST https://auth.riotgames.com/token` resulted in a `400 Bad Request` response:  

   WARN  {"error":"invalid_grant","error_description":"Invalid or expired authorization code, redirection URI mismatch, or PKCE v (truncated...).  
```
