### ISSUE TITLE
[BUG] Spectator V4 always returning 404 after patch 14.1

### ISSUE THREAD

**Issue by jlcarvalho** [RiotGames/developer-relations#876]
**Bug Description**  
Spectator V4 always returning 404 after patch 14.1.

**Problem Description**  
When we try to request infos about a player's match using the spectator v4 api, we always get `404 Data not found`.

**Expected Result**  
The API should return the expected match data.

**Actual Result**  
![Captura de Tela 2024-01-10 às 12 35 01](https://github.com/RiotGames/developer-relations/assets/1238663/42cdb45d-6bdd-4c42-af7e-c1a4aadbafaa)

**Developer Impact**  
Our App has some challenges based on the current match of the player, without this API we can't connect the match to the player in real time. Our app crashes when trying to finish the challenge, since there is no match connected.

* Frequency: Every API call
* Severity: My whole app is crashed right now.
* Cost: The challenges are the main purpose of the app, so, without this we can't run anything.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: Every user is creating support tickets to report the bug.

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: Every time a player tries to complete a challenge.
* Severity: My whole app is crashed right now.
* Quantity: There are 600 players that experienced this issue so far.
* Region: This affects players in BR.

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by tisbells** [comment]
Hey there - We're working on a resolution for Spectator issues and will provide an update as soon as we can.

**Comment by uncgopher** [comment]
This issue is also impacting twitch.tv/TrackingThePros - the stream is completely offline until fixed

**Comment by tisbells** [comment]
This should now be resolved, let us know if not

**Comment by omarali** [comment]
Spectator v4 active-games is working but spectator v4 featured-games is still broken

**Comment by tisbells** [comment]
Featured-games should be good to go now

**Comment by jlcarvalho** [comment]
Working as expected right now. Thanks.

**Comment by uncgopher** [comment]
Confirmed, thank you!

**Comment by hackoh** [comment]
@jlcarvalho 
Active game data is fine now.
But these game data cannot be spectated still.
For example, http://spectator-consumer.na1.lol.pvp.net:80/observer-mode/rest/consumer/getGameMetaData/NA1/4889990749/0/token
is returning 404 even this game is live.

**Comment by uncgopher** [comment]
About to dig into this more, but while the API endpoint is working and returning information, the command prompt that previously worked no longer does for launching spectator mode. Currently it launches a black screen but then nothing else happens; I also waited >5 minutes to make sure it wasn't the new spectator delay. Spectating works without issue when launching from the LOL client on the same PC.

Command prompt used (and I've tried multiple regions):
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator-consumer.euw1.lol.pvp.net:80 vGUEw+ZXk2ehfkVt52tCHmaNFSI/lFAb 6765375583 EUW1" "-UseRads"

**Comment by mrdotb** [comment]
I dig and I will save you some time.

The spectator api featured is now working but now they add TFT game inside. (not mentioned on a doc maybe a mistake)
```
"gameMode": "TFT"
```
The spectator api change subdomain.
```
    # "http://spectator-consumer.#{platform_id}.lol.pvp.net:8080" => before
    "http://spectator.#{platform_id}.lol.pvp.net:8080"

```

**Comment by hackoh** [comment]
use
```spectator spectator.euw1.lol.pvp.net:8080```
instead
```spectator spectator-consumer.euw1.lol.pvp.net:80```
but it takes a min for loading or timeout on my client.
any solutions?

**Comment by uncgopher** [comment]
Changing to
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.euw1.lol.pvp.net:8080 q4cbbB1u+Sc99+A6sDyCIJmp6rHiHMn6 6765379443 EUW1" "-UseRads"

Resulted in the game loading screen with players/champions being shown, but then I got an error saying spectator info could not be downloaded. Note that I changed the URL to "spectator.euw1" from "spectator-consumer" and updated the port to 8080.

Also, your comment about the TFT mode and then `"gameMode": "TFT"` - is that supposed to be added in there somewhere?

**Comment by uncgopher** [comment]
Confirmed the URL is the right one after capturing traffic when launching spectator from the client
![image](https://github.com/RiotGames/developer-relations/assets/2452637/f37b42a2-0735-46be-acbd-fd5d8a0acb96)

**Comment by uncgopher** [comment]
I was able to get a KR game to load:
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.kr.lol.pvp.net:8080 Hu9fWjgjaWSMZrknHXhBkc5BCEkzv611 6900641378 KR" "-UseRads"

It worked and with minimal loading time. However, an EUW game did not (Unable to download spectator data. The game will now exit):
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.euw1.lol.pvp.net:8080 GnXeOypzw92Plfg87I7Z3I6VO33zWwzE 6765448344 EUW1" "-UseRads"

For BR, it also failed, same as EUW:
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.br1.lol.pvp.net:8080 Mlh9SaJ8LpQgUTIKNUA3JdW4rZkVF1bV 2872698032 BR1" "-UseRads"

For NA, it failed:
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.na1.lol.pvp.net:8080 av+cn9ZkaY1DU613ml8PIyCknMpMsbdZ 4890472413 NA1" "-UseRads"

So potentially a server region issue? 

However, when I tried another KR game it also failed:
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.kr.lol.pvp.net:8080 kU77a6XMEX4KKvIDyBbfoNK28JCer6a7 6900667660 KR" "-UseRads"

**Comment by uncgopher** [comment]
And then trying the same KR game (last one listed above) then worked, so maybe an intermittent issue? Or potentially the game needs to have been playing longer, but that game was at least 5 minutes into it, and trying another game that's listed at 24 minutes currently fails too.

Then immediately after typing out the above, I was able to load a game that was only 4 minutes in:
cd "C:\Riot Games\League of Legends\Game\" & "League of Legends.exe" "spectator spectator.kr.lol.pvp.net:8080 XNJhOCwQ/QQUE0ZaqhS0MS2QOY4bhOhI 6900691272 KR" "-UseRads"

**Comment by hackoh** [comment]
Observers still look unstable.
They are affecting even spectating via client.

**Comment by andres66c** [comment]
> This issue is also impacting twitch.tv/TrackingThePros - the stream is completely offline until fixed

very true, although on YouTube there are channels like "lol korean pro replays", "Challenger replays", etc., that are uploading repetitions of this patch, apparently they managed to solve it!

**Comment by bangingheads** [comment]
> > This issue is also impacting twitch.tv/TrackingThePros - the stream is completely offline until fixed
> 
> very true, although on YouTube there are channels like "lol korean pro replays", "Challenger replays", etc., that are uploading repetitions of this patch, apparently they managed to solve it!

Replays are completely different than live spectating

**Comment by corysimmons** [comment]
If there are still problems with this can someone open up a new issue so Riot devs can put eyes on it?

**Comment by uncgopher** [comment]
Seems like things have stabilized - I haven't been getting that error any longer and the stream has been running without issue.

**Comment by VinventN** [comment]
I have been getting this error for about a week now.
