### ISSUE TITLE
[BUG] Riot RSO is blocking third party services as it says "An error occured please try again later"

### ISSUE THREAD

**Issue by katerlol** [RiotGames/developer-relations#960]
**Bug Description**  
Several people are having issues to successfully go through third party authorization services and end up wit the following message instead of being successfully redirected:
![image](https://github.com/user-attachments/assets/0cb801c1-f240-49ae-84fc-49251c193626)

**Problem Description**
I do not directly know the issue, but it seems like cloudflare is blocking requests from certain regions. It is not expected to block requests like this. 
![image](https://github.com/user-attachments/assets/3fd4b6fe-aa92-4ccf-808e-a09293aee134)
  
**Expected Result**  
I would expect to be successfully redirected to the callback-url. 

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: This affects ~ 10% of our users right now. It seems to be location based.
* Severity: The RSO Verification method is not usable for this issue. New users are not able to connect their accounts.

**Comment by Cypherous** [comment]
You blanked out the cloudflare ray ID which they will need to be able to look in to it, don't worry it doesn't contain anything that identifies you to anyone who doesn't have access to the cloudflare logs, in this instance riot games so you might want to post that if you still have it

You also don't specify which regions or if you're trying to access the game from a public/shared network like a university etc as cloudflare could be detecting other traffic on the network as a problem and just blocking people to avoid risk, i had that issue with akamai once which basically meant i couldn't access large chunks of the internet that were using their cloud service

**Comment by katerlol** [comment]
As mentioned in this discord message a Ray ID with the same error is 8a5eb14bd5282e9
https://discord.com/channels/187652476080488449/946641562757107782/1264012778872635455

Users impacted by this error for example located in finland. 

One of the impacted RSO can be found following this link: 
https://authenticate.riotgames.com/?client_id=riftq&method=riot_identity&platform=web&redirect_uri=https%3A%2F%2Fauth.riotgames.com%2Fauthorize%3Fclient_id%3Driftq%26redirect_uri%3Dhttps%253A%252F%252Friftq.com%252Faccount%252Fconnect%252Friotgames%252Foauth-callback%252F%26response_type%3Dcode%26scope%3Dopenid%252Coffline_access%252Ccpid%26state%3DXwnmLXl3UJR51ri9XVCIPhHZeLzyyreXOP27AOFE&security_profile=low

The network is not behind a VPN but the regular home network.

**Comment by ldrizze** [comment]
I can confirm it. I'm the author of Ray ID 8a5eb14bd5282e9. Almost all players that will use our application can't login based on Brazil location (38 ou 40 users).

Until today 07/20 6:49 PM UTC-3 still not working.

![image](https://github.com/user-attachments/assets/55f0b3d5-4856-4804-90d5-551070380def)

**Comment by Cypherous** [comment]
Are you able to login to the game just fine or does that block you too?

If both are blocked you're better off opening a support ticket

**Comment by Vidalee** [comment]
Can confirm my app is affected as well (app id [593254](https://developer.riotgames.com/app/593254/info) )
I could login fine until I unlinked the app in my riot account management page
![image](https://github.com/user-attachments/assets/ab8e35ef-099c-444d-a3e5-542ba40484d8)
Then I got this error:

https://github.com/user-attachments/assets/da0f9df8-f4d9-4426-861d-ba936af70828

Every new user is affected, no matter the game or account state, my guess is that this problem happened yesterday but it disappeared in 2 hours (or it could be on my side), but then at 10pm UTC 20/07/2024 the problem appeared and no user have been able to log since.

![chrome_6fsKBP6TG7](https://github.com/user-attachments/assets/81bb33bb-2f5e-4fc0-9862-7d2d981bc5ed)

Chart is in UTC+2

Location of users is mostly EU.

Additionally, I made a support request concering this bug with ID 103924456

**Comment by ldrizze** [comment]
> Are you able to login to the game just fine or does that block you too?
> 
> If both are blocked you're better off opening a support ticket

I'm able to log in to the game. It seems that is just the RSO (third-party authentication). Same for other users, they can log in to the game but can't proceed with RSO authentication.

**Comment by tisbells** [comment]
Hey there, we're looking into this! I'll post an update as soon as I have one.

**Comment by tisbells** [comment]
This should now be resolved, please let us know if not!

**Comment by serkanbal** [comment]
We still get reports that users are encountering this error while signing in with RSO. It seems like a rare occurrence, though.
Users say that the first time they try to sign in, they see the error page shared above. When I ask them to try again, they mostly (though not always) are able to sign in without any issue; but this seems like a pattern. I don't have any idea on how long they wait between the 1st and 2nd login attempts.
Other developers are talking about running into the same issue on the Third Party Developers Server on Discord. 
Here is the Riot ID of such a player: `Elrond87#5063` Hope it helps.

**Comment by katerlol** [comment]
I can confirm it also happened to one of our community members aswell.

**Comment by PenguinDevs** [comment]
I can confirm that this was a recurring issue which I've first received a case on 20/07/2024 from one of my users, and again on 21/07/2024 and a third time on 25/07/2024 which is after the X post https://x.com/RiotGamesDevRel/status/1815500290726015202

Among the ~200 successful RSO authorisations a day, those are all the cases that were raised.

**Comment by Vidalee** [comment]
Same here :)

**Comment by tisbells** [comment]
Hey there, I let the team know this was still a problem and they put out another update that will hopefully resolve the lingering issues for the most part. Let us know.

**Comment by DoohoLee-GGQ** [comment]
same here

**Comment by binnyboi-amsterdam** [comment]
I hope Riot would do smth on this asap, otherwise they'd get some riot from me and all these ppl LMAO
